name: Main workflow

on:
  push:
    paths-ignore:
      - '**/README.md'
env:
    VAR: |
        run echo hi
jobs:
  telegram_message:
    name: Send telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get previous commit
        id: get_commit
        run: |
          PREVIOUS_COMMIT=$(git log -1 --pretty=format:"%h")
          echo "::set-output name=previous_commit::$PREVIOUS_COMMIT"

      - name: Get Changes
        id: changes
        run: |
          CHANGES=$(git diff ${{ steps.get_commit.outputs.previous_commit }}~1) 
          echo "::set-output name=changes::$CHANGES"

      - uses: actions/checkout@master
      - name: send custom message with message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message:
            Workflow ${{ github.workflow }}

            Репозиторий ${{ github.event.repository.full_name }}

            Автор ${{ github.actor }}

            Список изменений ${{steps.changes.outputs.changes }}.
