name: Main workflow

on:
  push:
    paths-ignore:
      - '**/README.md'
env:
    VAR: |
        run echo hi
jobs:
  telegram_message:
    name: Send telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Get Changes
        id: changes
        run: |
          CHANGES=$(git log --pretty=format:"%h - %s (%an)" ${{ github.event.before }}..${{ github.sha }})
          echo "::set-output name=changes::$CHANGES"

      - uses: actions/checkout@master
      - name: send custom message with message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message:
            Workflow ${{ github.workflow }}

            Репозиторий ${{ github.event.repository.full_name }}

            Автор ${{ github.actor }}

            Изменения ${{steps.changes.outputs.changes }}.
